#!/bin/sh
setup=0

COLOR_BACKGROUND="#282a2e"
COLOR_PRIMARY="#fefefe"
COLOR_SECONDARY="#81a2be"
BORDER=2

hsetroot -solid $COLOR_BACKGROUND &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xdefaults

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x xss-lock > /dev/null || xss-lock slock &
#pgrep -x bg.sh > /dev/null || $HOME/.scripts/bg.sh > /dev/null &

[ -f "$HOME/.config/xrandr.sh" ] && . $HOME/.config/xrandr.sh

primary=$(bspc query --monitors -m primary)
set -- a b c d e f g h i j k l m n o 
for m in $primary $(bspc query -M | grep -v $primary); do
    echo "adding monitor $m as $1"
    bspc monitor $m -n $1 
    shift 1
done

for m in $(bspc query -M --names); do
    bspc monitor $m -d ${m}1 ${m}2 ${m}3 ${m}4 ${m}5 ${m}6 ${m}7 ${m}8 ${m}9
done


$HOME/.config/polybar/launch.sh &

bspc config border_width	$BORDER
bspc config window_gap		0
$HOME/.scripts/toggle-gap.sh

bspc config focus_follows_pointer false
 
bspc config normal_border_color "$COLOR_PRIMARY"
bspc config active_border_color "$COLOR_PRIMARY"
bspc config focused_border_color "$COLOR_SECONDARY"
wmname bspwm 

$HOME/.scripts/start-mpd
