#!/bin/sh

COLOR_BACKGROUND="#151515"
COLOR_PRIMARY="#f58f44"
COLOR_SECONDARY="#5977b3"

xsetroot -cursor_name left_ptr &
xrdb ~/.Xdefaults

bspc monitor  -d a1 a2 a3 a4 a5 a6 a7 a8 a9

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x xss-lock > /dev/null || xss-lock slock &

$HOME/.config/polybar/launch.sh
$HOME/.scripts/bg.sh

bspc config border_width	1
bspc config window_gap		0

bspc config focus_follows_pointer false
 
bspc config normal_border_color "$COLOR_BACKGROUND"
bspc config active_border_color "$COLOR_BACKGROUND"
bspc config focused_border_color "$COLOR_PRIMARY"
wmname bspwm 

urxvt &

$HOME/.scripts/start-mpd
