#!/bin/bash

chosen=$(dmenu -i -l 20 < ~/.local/share/emoji | sed "s/ .*//")

[ "$chosen" != "" ] || exit

# If you run this command with an argument, it will automatically insert the character.
echo "$chosen" | xclip -selection clipboard
if [ -n "$1" ]; then
	WINDOW=$(xdotool getactivewindow getwindowname)
	if [[ "$WINDOW" =~ .*"$SUB".* ]]; then
		xdotool key "ctrl+v" 
	else
		xdotool key Shift+Insert
	fi
#	xdotool type --delay 1 $chosen

#	VAR=$(xclip -o)

#	xdotool type $chosen
else
	notify-send "'$chosen' copied to clipboard." &
fi
