#!/bin/sh


SEARCH_ENGINE="https://search.brave.com/search?q="
SEARCH_HISTORY=/tmp/.search_history

SEARCH=$(cat $SEARCH_HISTORY | dmenu -p "search")

touch $SEARCH_HISTORY

cat <<< "$SEARCH
$(cat $SEARCH_HISTORY)" > $SEARCH_HISTORY

brave "$SEARCH_ENGINE$SEARCH"
