#!/bin/sh

default_browser="links-launcher"
BROWSER=${BROWSER:-$default_browser}
SEARCH_ENGINE="https://search.davidovski.xyz/search.php?q="
SEARCH_HISTORY=$HOME/.local/share/search_history

SEARCH=$(cat $SEARCH_HISTORY | dmenu -p "search")

echo "$SEARCH" >> $SEARCH_HISTORY

query=$(echo $SEARCH | sed 's/ /+/g')

echo $query | grep -q '(?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)' && {
    $BROWSER "$query"
} ||  {
    $BROWSER "$SEARCH_ENGINE$query"
}
