#!/bin/sh
read title 
clear
columns=$(tput cols)
rows=$(tput lines)
tput clear
y=$((($columns-$(echo -n $title | head -1 | wc -c))/2))
x=$((($rows-$(echo $title | wc -l))/2))

while read p; do
	tput cup $x $y
	echo "$p"
	x=$((x+1))

done <<< "$title";

tput cup $rows 0
